###
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "name": "테스트 이름",
  "email": "테스트 이메일",
  "password": "테스트 비밀번호"
}

###
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "email": "테스트 이메일",
  "password": "테스트 비밀번호"
}

###
GET http://localhost:8080/users

###
GET http://localhost:8080/users/1

###
PUT http://localhost:8080/users/2
Content-Type: application/json

{
  "name": "테스트 이름 수정",
  "email": "테스트 이메일 수정"
}

###
DELETE http://localhost:8080/users/1